import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ur";

const translations = {
  en: {
    appName: "AgriCheck",
    dashboard: "Dashboard",
    aiAdvisor: "AI Advisor",
    soilHistory: "Soil History",
    settings: "Settings",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    ph: "pH Level",
    soilTemp: "Soil Temperature",
    humidity: "Humidity",
    ec: "EC (Conductivity)",
    live: "Live",
    sensorOverview: "Sensor Overview",
    realTimeMonitoring: "Real-time soil monitoring from ESP32",
    login: "Login",
    signup: "Sign Up",
    email: "Email",
    password: "Password",
    welcomeBack: "Welcome Back",
    loginSubtitle: "Sign in to your AgriCheck dashboard",
    createAccount: "Create Account",
    signupSubtitle: "Start monitoring your soil health",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    logout: "Logout",
    mgPerKg: "mg/kg",
    celsius: "°C",
    percent: "%",
    msPerCm: "mS/cm",
    aiListening: "Listening...",
    aiTapToSpeak: "Tap to speak with AI Advisor",
    soilHealthScore: "Soil Health Score",
    aiAdvisorHeading: "AI Voice Advisor",
    aiAdvisorSubheading: "Speak in Urdu or English for personalized farm recommendations",
    soilHistoryHeading: "Soil History",
    soilHistorySubheading: "Historical sensor data and trends",
    settingsHeading: "Settings",
    settingsSubheading: "Manage your account preferences",
    getAiRecommendationTitle: "Get AI Recommendations",
    getAiRecommendationDescription: "Ask our AI advisor for personalized farming guidance",
    good: "Good",
    optimal: "Optimal",
    high: "High",
    low: "Low",
    moderate: "Moderate",
    name: "Full Name",
    // Static page navbar
    navHome: "Home",
    navAbout: "About",
    navServices: "Services",
    navTestimonials: "Testimonials",
    navContact: "Contact",
    navDashboard: "Dashboard",
    langToggleLabel: "اردو",
    connected: "Connected",

    // Dashboard additions
    analytics: "Analytics",
    sensorMetricsOverview: "Sensor Metrics Overview",
    normalizedReadings: "Normalized sensor readings against optimal ranges",
    currentVsOptimalLevels: "Current vs Optimal Levels",
    comparisonValues: "Comparison of current values with optimal and maximum ranges",
    soilHealthStatus: "Soil Health Status",
    detailedHealthAssessment: "Detailed health assessment based on all metrics",
    excellent: "Excellent",
    needsImprovement: "Needs Improvement",
    openAiAdvisor: "Open AI Advisor",
    healthScoreLabel: "Health Score",
    nutrients: "Nutrients",
    ideal: "Ideal",
    moisture: "Moisture",
    loadingSensorData: "Loading sensor data...",
    failedToFetchData: "Failed to fetch sensor data. Please ensure the backend is running.",
    current: "Current",
    temperature: "Temperature",

    // AI Advisor additions
    voiceAdvisorReady: "Voice Advisor ready. Connect to start speaking.",
    connectingToVoiceAdvisor: "Connecting to Voice Advisor...",
    connectedToVoiceAdvisor: "Connected to Voice Advisor",
    youSaid: "You said",
    micMutedAiResponding: "Mic muted — AI is responding...",
    micUnmutedSpeakNow: "Mic unmuted — speak now",
    audioReceivedPlaying: "Audio received, playing...",
    disconnected: "Disconnected",
    websocketFailed: "WebSocket connection failed",
    welcomeChat: "Welcome to AI Advisor chat. Ask questions about your crops, soil, and farm, and get recommendations.",
    typeQuestionPlaceholder: "Type your question...",
    aiChatAssistant: "Ai Chat Assistant",
    connect: "Connect",
    disconnect: "Disconnect",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    controls: "Controls",
    landSizeAcres: "Land Size (acres)",
    updateConfig: "Update Config",
    audioPlayback: "Audio Playback",
    audioInstructions: "Audio will appear here when AI responds",
    messages: "Messages",
    message: "message",
    messagesPlural: "messages",
    languageLabel: "Language",
    connecting: "Connecting...",
    recordingSpeakNow: "Recording... Speak now!",

    // Soil History additions
    avgN: "Avg N",
    avgPh: "Avg pH",
    avgTemp: "Avg Temp",
    avgHumidity: "Avg Humidity",
    filterByDate: "Filter by Date",
    recordsToDisplay: "Records to Display",
    clearFilter: "Clear Filter",
    exportCsv: "Export CSV",
    historicalReadings: "Historical Readings",
    displayingRecords: "Displaying {count} of {total} total records",
    noReadingsFound: "No readings found for the selected date",
    timestamp: "Timestamp",
    nitrogenRange: "Nitrogen Range",
    phRange: "pH Range",
    temperatureRange: "Temperature Range",
    ecRange: "EC Range",
    min: "Min",
    max: "Max",
    last20Records: "Last 20 records",
    last50Records: "Last 50 records",
    last100Records: "Last 100 records",
    last200Records: "Last 200 records",
    loadingHistoricalData: "Loading historical data...",
    noDataAvailable: "No sensor data available yet",
    uploadFirst: "Please upload sensor data first to view history",

    // Settings additions
    accountInformation: "Account Information",
    currentlyLoggedInAs: "Currently logged in as",
    updateUsername: "Update Username",
    changeDisplayName: "Change your display name",
    editUsername: "Edit Username",
    newUsername: "New Username",
    save: "Save",
    cancel: "Cancel",
    enterNewUsername: "Enter new username",
    enterNewEmail: "Enter new email",
    enterYourPassword: "Enter your password",
    saving: "Saving...",
    updateEmail: "Update Email",
    changeEmailAddress: "Change your email address",
    editEmail: "Edit Email",
    newEmail: "New Email",
    currentPasswordVerification: "Current Password (for verification)",
    updatePassword: "Update Password",
    changeAccountPassword: "Change your account password",
    editPassword: "Edit Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    min6Chars: "Minimum 6 characters",
    usernameCannotBeEmpty: "Username cannot be empty",
    usernameUpdatedSuccess: "Username updated successfully!",
    emailPasswordRequired: "Email and password are required",
    invalidEmailFormat: "Invalid email format",
    emailUpdatedSuccess: "Email updated successfully!",
    incorrectPassword: "Incorrect password",
    emailAlreadyInUse: "Email already in use",
    currentPasswordRequired: "Current Password is required",
    passwordMin6Chars: "New password must be at least 6 characters",
    passwordsDoNotMatch: "Passwords do not match",
    passwordMustBeDifferent: "New password must be different from current password",
    passwordUpdatedSuccess: "Password updated successfully!",
    incorrectCurrentPassword: "Incorrect current password",
    topRecommendedCrops: "Top 3 Recommended Crops",
    basedOnLiveSensorData: "Based on live sensor data",
    analyzingSoilData: "Analyzing soil data…",
    getMoreInfo: "Get More Info →",
  },
  ur: {
    appName: "ایگری چیک",
    dashboard: "ڈیش بورڈ",
    aiAdvisor: "اے آئی مشیر",
    soilHistory: "مٹی کی تاریخ",
    settings: "ترتیبات",
    nitrogen: "نائٹروجن (N)",
    phosphorus: "فاسفورس (P)",
    potassium: "پوٹاشیم (K)",
    ph: "پی ایچ لیول",
    soilTemp: "مٹی کا درجہ حرارت",
    humidity: "نمی",
    ec: "ای سی (چالکتا)",
    live: "لائیو",
    sensorOverview: "سینسر کا جائزہ",
    realTimeMonitoring: "ESP32 سے ریئل ٹائم مٹی کی نگرانی",
    login: "لاگ ان",
    signup: "سائن اپ",
    email: "ای میل",
    password: "پاس ورڈ",
    welcomeBack: "خوش آمدید",
    loginSubtitle: "اپنے ایگری چیک ڈیش بورڈ میں سائن ان کریں",
    createAccount: "اکاؤنٹ بنائیں",
    signupSubtitle: "اپنی مٹی کی صحت کی نگرانی شروع کریں",
    noAccount: "کوئی اکاؤنٹ نہیں ہے؟",
    haveAccount: "پہلے سے اکاؤنٹ ہے؟",
    logout: "لاگ آؤٹ",
    mgPerKg: "ملی گرام/کلوگرام",
    celsius: "°سی",
    percent: "%",
    msPerCm: "ایم ایس/سی ایم",
    aiListening: "سن رہا ہے...",
    aiTapToSpeak: "اے آئی مشیر سے بات کرنے کے لیے ٹیپ کریں",
    soilHealthScore: "مٹی کی صحت کا اسکور",
    aiAdvisorHeading: "اے آئی وائس ایڈوائزر",
    aiAdvisorSubheading: "ذاتی فصل کی رہنمائی کے لیے اردو یا انگریزی میں بولیں",
    soilHistoryHeading: "مٹی کی تاریخ",
    soilHistorySubheading: "تاریخی سینسر ڈیٹا اور رجحانات",
    settingsHeading: "ترتیبات",
    settingsSubheading: "اپنے اکاؤنٹ کی ترجیحات کا انتظام کریں",
    getAiRecommendationTitle: "اے آئی سفارشات حاصل کریں",
    getAiRecommendationDescription: "اپنے فارمنگ کی ذاتی رہنمائی کے لیے ہمارے اے آئی مشیر سے پوچھیں",
    good: "اچھا",
    optimal: "بہترین",
    high: "زیادہ",
    low: "کم",
    moderate: "معتدل",
    name: "پورا نام",
    // Static page navbar
    navHome: "ہوم",
    navAbout: "ہمارے بارے میں",
    navServices: "خدمات",
    navTestimonials: "تجربات",
    navContact: "رابطہ",
    navDashboard: "ڈیش بورڈ",
    langToggleLabel: "English",
    connected: "منسلک",

    // Dashboard additions
    analytics: "تجزیات",
    sensorMetricsOverview: "سینسر میٹرکس کا جائزہ",
    normalizedReadings: "بہترین حدود کے مقابلے میں معمول کے مطابق سینسر ریڈنگز",
    currentVsOptimalLevels: "موجودہ بمقابلہ بہترین لیولز",
    comparisonValues: "موجودہ اقدار کا بہترین اور زیادہ سے زیادہ حدود کے ساتھ موازنہ",
    soilHealthStatus: "مٹی کی صحت کی صورتحال",
    detailedHealthAssessment: "تمام میٹرکس کی بنیاد پر صحت کا تفصیلی جائزہ",
    excellent: "بہترین",
    needsImprovement: "بہتری کی ضرورت ہے",
    openAiAdvisor: "اے آئی ایڈوائزر کھولیں",
    healthScoreLabel: "صحت کا اسکور",
    nutrients: "غذائی اجزاء",
    ideal: "مثالی",
    moisture: "نمی",
    loadingSensorData: "سینسر ڈیٹا لوڈ ہو رہا ہے...",
    failedToFetchData: "سینسر ڈیٹا حاصل کرنے میں ناکامی۔ براہ کرم یقینی بنائیں کہ بیک اینڈ چل رہا ہے۔",
    current: "موجودہ",
    temperature: "درجہ حرارت",

    // AI Advisor additions
    voiceAdvisorReady: "وائس ایڈوائزر تیار ہے۔ بات شروع کرنے کے لیے جڑیں۔",
    connectingToVoiceAdvisor: "وائس ایڈوائزر سے جڑ رہا ہے...",
    connectedToVoiceAdvisor: "وائس ایڈوائزر سے منسلک ہو گیا",
    youSaid: "آپ نے کہا",
    micMutedAiResponding: "مائیک خاموش ہے — اے آئی جواب دے رہا ہے...",
    micUnmutedSpeakNow: "مائیک آن ہے — اب بولیں",
    audioReceivedPlaying: "آڈیو موصول ہوئی، چل رہی ہے...",
    disconnected: "منقطع ہو گیا",
    websocketFailed: "ویب ساکٹ کنکشن ناکام ہو گیا",
    welcomeChat: "اے آئی ایڈوائزر چیٹ میں خوش آمدید۔ اپنی فصلوں، مٹی اور فارم کے بارے میں سوالات پوچھیں، اور سفارشات حاصل کریں۔",
    typeQuestionPlaceholder: "اپنا سوال لکھیں...",
    aiChatAssistant: "اے آئی چیٹ اسسٹنٹ",
    connect: "کنیکٹ کریں",
    disconnect: "منقطع کریں",
    startRecording: "ریکارڈنگ شروع کریں",
    stopRecording: "ریکارڈنگ روک دیں",
    controls: "کنٹرولز",
    landSizeAcres: "زمین کا سائز (ایکڑ)",
    updateConfig: "ترتیبات اپ ڈیٹ کریں",
    audioPlayback: "آڈیو پلے بیک",
    audioInstructions: "جب اے آئی جواب دے گا تو آڈیو یہاں نظر آئے گی",
    messages: "پیغامات",
    message: "پیغام",
    messagesPlural: "پیغامات",
    languageLabel: "زبان",
    connecting: "جڑ رہا ہے...",
    recordingSpeakNow: "ریکارڈنگ ہو رہی ہے... اب بولیں!",

    // Soil History additions
    avgN: "اوسط نائٹروجن",
    avgPh: "اوسط پی ایچ",
    avgTemp: "اوسط درجہ حرارت",
    avgHumidity: "اوسط نمی",
    filterByDate: "تاریخ کے لحاظ سے فلٹر کریں",
    recordsToDisplay: "دکھائے جانے والے ریکارڈز",
    clearFilter: "فلٹر ختم کریں",
    exportCsv: "ایکسپورٹ CSV",
    historicalReadings: "تاریخی ریڈنگز",
    displayingRecords: "کل {total} میں سے {count} ریکارڈز دکھائے جا رہے ہیں",
    noReadingsFound: "منتخب کردہ تاریخ کے لیے کوئی ریڈنگ نہیں ملی",
    timestamp: "ٹائم سٹیمپ",
    nitrogenRange: "نائٹروجن کی حد",
    phRange: "پی ایچ کی حد",
    temperatureRange: "درجہ حرارت کی حد",
    ecRange: "EC کی حد",
    min: "کم سے کم",
    max: "زیادہ سے زیادہ",
    last20Records: "آخری 20 ریکارڈز",
    last50Records: "آخری 50 ریکارڈز",
    last100Records: "آخری 100 ریکارڈز",
    last200Records: "آخری 200 ریکارڈز",
    loadingHistoricalData: "تاریخی ڈیٹا لوڈ ہو رہا ہے...",
    noDataAvailable: "ابھی تک کوئی سینسر ڈیٹا دستیاب نہیں ہے",
    uploadFirst: "تاریخ دیکھنے کے لیے پہلے سینسر ڈیٹا اپ لوڈ کریں",

    // Settings additions
    accountInformation: "اکاؤنٹ کی معلومات",
    currentlyLoggedInAs: "فی الحال اس اکاؤنٹ سے لاگ ان ہیں",
    updateUsername: "صارف کا نام اپ ڈیٹ کریں",
    changeDisplayName: "اپنا نام تبدیل کریں",
    editUsername: "صارف نام تبدیل کریں",
    newUsername: "نیا صارف نام",
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    enterNewUsername: "نیا صارف نام درج کریں",
    enterNewEmail: "نیا ای میل درج کریں",
    enterYourPassword: "اپنا پاس ورڈ درج کریں",
    saving: "محفوظ ہو رہا ہے...",
    updateEmail: "ای میل اپ ڈیٹ کریں",
    changeEmailAddress: "اپنا ای میل پتہ تبدیل کریں",
    editEmail: "ای میل تبدیل کریں",
    newEmail: "نیا ای میل",
    currentPasswordVerification: "موجودہ پاس ورڈ (تصدیق کے لیے)",
    updatePassword: "پاس ورڈ اپ ڈیٹ کریں",
    changeAccountPassword: "اپنے اکاؤنٹ کا پاس ورڈ تبدیل کریں",
    editPassword: "پاس ورڈ تبدیل کریں",
    currentPassword: "موجودہ پاس ورڈ",
    newPassword: "نیا پاس ورڈ",
    confirmNewPassword: "نئے پاس ورڈ کی تصدیق کریں",
    min6Chars: "کم از کم 6 حروف",
    usernameCannotBeEmpty: "صارف کا نام خالی نہیں ہو سکتا",
    usernameUpdatedSuccess: "صارف کا نام کامیابی سے اپ ڈیٹ ہو گیا!",
    emailPasswordRequired: "ای میل اور پاس ورڈ درکار ہیں",
    invalidEmailFormat: "ای میل کا فارمیٹ غلط ہے",
    emailUpdatedSuccess: "ای میل کامیابی سے اپ ڈیٹ ہو گیا!",
    incorrectPassword: "غلط پاس ورڈ",
    emailAlreadyInUse: "ای میل پہلے ہی استعمال میں ہے",
    currentPasswordRequired: "موجودہ پاس ورڈ درکار ہے",
    passwordMin6Chars: "نیا پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے",
    passwordsDoNotMatch: "پاس ورڈ مماثلت نہیں رکھتے",
    passwordMustBeDifferent: "نیا پاس ورڈ موجودہ پاس ورڈ سے مختلف ہونا چاہیے",
    passwordUpdatedSuccess: "پاس ورڈ کامیابی سے اپ ڈیٹ ہو گیا!",
    incorrectCurrentPassword: "غلط موجودہ پاس ورڈ",
    topRecommendedCrops: "ٹاپ 3 تجویز کردہ فصلیں",
    basedOnLiveSensorData: "لائیو سینسر ڈیٹا پر مبنی",
    analyzingSoilData: "مٹی کے ڈیٹا کا تجزیہ ہو رہا ہے...",
    getMoreInfo: "مزید معلومات حاصل کریں →",
  },
};

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, params?: Record<string, string | number>) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en");
  const dir = language === "ur" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", language);
  }, [language, dir]);

  const t = (key: TranslationKey, params?: Record<string, string | number>) => {
    let translation = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        translation = translation.replace(`{${k}}`, String(v));
      });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};